presets:
  tv:
    private_torrents: no

    regexp:
      reject:
        - sub[s][\s\._]: {from: title}  # Bloquea todos los torrent que contengan la palabra sub(s) (subtitulos=
        - ^\[[^\]]+\]: {from: title}    # Bloquea todos los torrent con este patrón en su titulo "[ <algo> ]"
        - 3D: {from: title}             # Bloquea todos los torrent con la palabra 3D en su título. (no tengo 3D)
        - R5: {from: title}             # Las siguientes expresiones intentan detectar torrents que tengan una calidad pobre.
        - WEBSCR: {from: title}         
        - Cam: {from: title}

    content_filter:
      require:
        - '*.mkv'

    exec:
      auto_escape: yes
      on_output:
        for_accepted: /home/stefano/scripts/startDownload.sh "{{title}}" "{{path}}"
    series:
      settings:
        tv:
          exact: yes
          propers: 3 days
          quality: 720p+
          set:
            path: /media/stuff/series/{{series_name}}/Season {{"%02d"|format(series_season)}}/
            label: "{{series_name}}"
      tv:
        - Falling Skies
        - Game of Thrones
        - Arrow
        - Revolution
        - The Walking Dead
        - Nikita
        - Continuum
        - Defiance
        - Beware the batman
        - Elementary
        - The Legend of Korra

    transmission:
      enabled: yes
      host: localhost
      port: 9091
      username: transmission
      password: transmission
      removewhendone: no

   #mark acquired in trak.tv
    trakt_acquired:
      username: sssalvatori
      api_key: 348c47e94dbbe5535057aa1f515934ca
      password: pw236980
      type: series

tasks:
  bt-chat.com-tv:
    priority: 2
    rss: http://rss.bt-chat.com/?group=3
    preset: tv

  ezrss.it:
    priority: 1
    rss: http://ezrss.it/feed/
    preset: tv

  thepiratebay.org-tv:
    priority: 3
    rss: http://rss.thepiratebay.org/208
    preset: tv
    verify_ssl_certificates: no

  kat.ph-tv:
    priority: 4
    rss: http://kat.ph/tv/?rss=1
    preset: tv

  extratorrent.com-tv:
    priority: 5
    rss: http://extratorrent.com/rss.xml?cid=8
    preset: tv

  torrentz.eu-tv:
    priority: 6
    rss: http://torrentz.eu/feed
    preset: tv

