templates:
  tv:
    private_torrents: no
    regexp:
      reject:
        - sub[s][\s\._]: {from: title}  # Bloquea todos los torrent que contengan la palabra sub(s) (subtitulos=
#        - '\[[^\]]+\].*': {from: title}    # Bloquea todos los torrent con este patrón en su titulo "[ <algo> ]"
        - 3D: {from: title}             # Bloquea todos los torrent con la palabra 3D en su título. (no tengo 3D)
        - R5: {from: title}             # Las siguientes expresiones intentan detectar torrents que tengan una calidad pobre.
        - WEBSCR: {from: title}         
        - Cam: {from: title}
        - '(?x) (?:_|\b) (?: afg | msd | (\{?)c[_ ]p\1 | pimp4003 ) $': {from: title}

    content_filter:
      require: [ '*.avi', '*.mkv', '*.mp4' ]

    pushover:
      userkey: 
       - USERKEY 
      apikey: APIKEY
      title: Downloading {{series_name}}
      message: Episode {{series_id}} {{title}}
      priority: 1
      sound: incoming
    series:
      settings:
        tv:
          exact: yes
          propers: 3 days
          quality: 720p+
          set:
            path: /media/stuff/series/{{series_name}}/Season {{"%02d"|format(series_season)}}/
            label: "{{series_name}}"
        anime:
          exact: yes
          quality: 720p+
          set:
            path: /media/stuff/series/{{series_name}}/Season {{"%02d"|format(series_season)}}/
            label: "{{series_name}}"
      tv:
        - Falling Skies
        - Game of Thrones
        - Arrow
        - Revolution
        - The Walking Dead
        - Nikita
        - Continuum
        - Defiance
        - Marvels Agents of S H I E L D
        - The Legend of Korra
        - Avenger Assemble
        - Black Sails
        - Intelligence
        - Vikings
        - Cosmos A Space-Time Odyssey

    clean_transmission:
      host: localhost
      port: 9091
      username: transmission
      password: transmission
      min_ratio: 1

   #mark acquired in trak.tv
    trakt_add:
      username: 
      api_key: 
      password: 
      list: library

tasks:

  bt-chat.com-tv:
    priority: 2
    rss: http://rss.bt-chat.com/?group=3
    template: tv

  ezrss.it:
    priority: 1
    rss: http://ezrss.it/feed/
    template: tv

  thepiratebay.org-tv:
    priority: 3
    rss: http://rss.thepiratebay.org/208
    template: tv
    verify_ssl_certificates: no
